"""edited Reader model

Revision ID: 2aa170d36a27
Revises: babfa5efe913
Create Date: 2025-06-20 17:42:58.490919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa170d36a27'
down_revision: Union[str, None] = 'babfa5efe913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('readers_name_key'), 'readers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('readers_name_key'), 'readers', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
