"""added Book and Borrow models

Revision ID: babfa5efe913
Revises: cebbc4b96357
Create Date: 2025-06-20 14:21:59.720492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'babfa5efe913'
down_revision: Union[str, None] = 'cebbc4b96357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('borrows', 'return_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'return_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
